name: CI

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing Yarn
        run: npm install -g yarn
      - name: Testing frontend
        run: |
          cd frontend/
          yarn install
          yarn lint && yarn test --watchAll=false --ci
      - name: Build Frontend
        run: |
          cd frontend/
          yarn install
          yarn build
